create table if not exists public.member_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  home_city text,
  points integer not null default 0,
  reputation_level text not null default 'New Member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.points_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  points integer not null check (points <> 0),
  reference_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists points_ledger_user_action_reference_unique
  on public.points_ledger(user_id, action, reference_key)
  where reference_key is not null;

create table if not exists public.activity_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  venue_id uuid not null references public.venues(id) on delete cascade,
  status text not null check (status in ('active', 'packed', 'quiet', 'line_short', 'line_medium', 'line_long', 'parking_easy', 'parking_hard')),
  verified_nearby boolean not null default false,
  expires_at timestamptz not null default (now() + interval '2 hours'),
  created_at timestamptz not null default now()
);

create index if not exists activity_reports_venue_recent_idx
  on public.activity_reports(venue_id, created_at desc);
create index if not exists activity_reports_user_recent_idx
  on public.activity_reports(user_id, created_at desc);

create table if not exists public.owner_signup_notifications (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  provider text,
  notified_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.member_profiles enable row level security;
alter table public.points_ledger enable row level security;
alter table public.activity_reports enable row level security;
alter table public.owner_signup_notifications enable row level security;

drop policy if exists "members can read own profile" on public.member_profiles;
create policy "members can read own profile" on public.member_profiles
  for select using (auth.uid() = user_id);
drop policy if exists "members can update own profile" on public.member_profiles;
create policy "members can update own profile" on public.member_profiles
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "members can read own points" on public.points_ledger;
create policy "members can read own points" on public.points_ledger
  for select using (auth.uid() = user_id);
drop policy if exists "members can read own activity reports" on public.activity_reports;
create policy "members can read own activity reports" on public.activity_reports
  for select using (auth.uid() = user_id);

create or replace function public.refresh_member_points(target_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  total integer;
  next_level text;
begin
  select coalesce(sum(points), 0)::integer into total
  from public.points_ledger
  where user_id = target_user;

  next_level := case
    when total >= 1000 then '757 Insider'
    when total >= 500 then 'Trusted Local'
    when total >= 200 then 'Contributor'
    when total >= 75 then 'Local'
    else 'New Member'
  end;

  insert into public.member_profiles(user_id, points, reputation_level)
  values (target_user, total, next_level)
  on conflict (user_id) do update
    set points = excluded.points,
        reputation_level = excluded.reputation_level,
        updated_at = now();
end;
$$;
