create extension if not exists pgcrypto;

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  expiration_time timestamptz,
  p256dh text not null,
  auth text not null,
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_id_idx
  on public.push_subscriptions (user_id)
  where enabled = true;

alter table public.push_subscriptions enable row level security;

create table if not exists public.push_deliveries (
  id bigint generated by default as identity primary key,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  venue_id uuid references public.venues(id) on delete set null,
  alert_key text not null,
  delivered_at timestamptz not null default now(),
  unique (subscription_id, alert_key)
);

create index if not exists push_deliveries_recent_idx
  on public.push_deliveries (subscription_id, delivered_at desc);

alter table public.push_deliveries enable row level security;

comment on table public.push_subscriptions is
  'Private standards-based Web Push subscriptions. Accessed only by server routes using the service role.';

comment on table public.push_deliveries is
  'Notification delivery ledger used to prevent duplicate saved-place alerts.';
