create table if not exists public.buzz_score_history (
  id bigint generated by default as identity primary key,
  venue_id uuid not null references public.venues(id) on delete cascade,
  score smallint not null check (score >= 0 and score <= 100),
  label text not null,
  score_mode text not null check (score_mode in ('live','forecast')),
  confidence text not null check (confidence in ('low','medium','high')),
  version text not null,
  computed_at timestamptz not null,
  expires_at timestamptz not null,
  evidence_age_minutes integer,
  source_families text[] not null default '{}',
  explanation text not null,
  factors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique (venue_id, computed_at)
);

create index if not exists buzz_score_history_venue_time_idx
on public.buzz_score_history(venue_id, computed_at desc);

create index if not exists buzz_score_history_time_score_idx
on public.buzz_score_history(computed_at desc, score desc);

alter table public.buzz_score_history enable row level security;
-- Historical model evidence is server-side only. The app reads the sanitized
-- current snapshot; calibration endpoints require a private secret.
