-- Buzz pilot data stack: provider mappings, expiring evidence, score snapshots,
-- partner pulses, user reports, and manual ground truth.

create extension if not exists pgcrypto;

create table if not exists public.buzz_provider_venues (
  id bigint generated by default as identity primary key,
  venue_id uuid not null references public.venues(id) on delete cascade,
  provider text not null,
  external_id text,
  coverage_status text not null default 'pending' check (coverage_status in ('pending','covered','forecast_only','no_data','error','disabled')),
  last_checked_at timestamptz,
  last_success_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (venue_id, provider),
  unique (provider, external_id)
);

create table if not exists public.buzz_provider_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  venue_id uuid references public.venues(id) on delete cascade,
  provider text not null,
  external_id text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, provider),
  unique (provider, external_id)
);

create table if not exists public.buzz_signal_snapshots (
  id bigint generated by default as identity primary key,
  venue_id uuid not null references public.venues(id) on delete cascade,
  source text not null,
  signal_family text not null,
  signal_type text not null,
  value numeric not null,
  is_live boolean not null default false,
  confidence numeric not null default 0.5 check (confidence >= 0 and confidence <= 1),
  observed_at timestamptz not null,
  expires_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (venue_id, source, signal_type, observed_at)
);

create table if not exists public.buzz_score_snapshots (
  venue_id uuid primary key references public.venues(id) on delete cascade,
  score smallint not null check (score >= 0 and score <= 100),
  label text not null,
  score_mode text not null check (score_mode in ('live','forecast')),
  confidence text not null check (confidence in ('low','medium','high')),
  version text not null default 'buzz-v1',
  computed_at timestamptz not null,
  expires_at timestamptz not null,
  evidence_age_minutes integer,
  source_families text[] not null default '{}',
  explanation text not null,
  factors jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.venue_partner_pulses (
  id uuid primary key default gen_random_uuid(),
  venue_id uuid not null references public.venues(id) on delete cascade,
  occupancy_band text not null check (occupancy_band in ('quiet','steady','busy','packed')),
  occupancy_pct smallint check (occupancy_pct is null or (occupancy_pct >= 0 and occupancy_pct <= 100)),
  wait_minutes integer check (wait_minutes is null or wait_minutes >= 0),
  reservations_status text,
  tickets_status text,
  submitted_by text,
  verified boolean not null default false,
  observed_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.buzz_user_reports (
  id uuid primary key default gen_random_uuid(),
  venue_id uuid not null references public.venues(id) on delete cascade,
  user_id uuid,
  device_hash text,
  crowd_level text not null check (crowd_level in ('quiet','steady','busy','packed')),
  reported_lat numeric,
  reported_lng numeric,
  distance_meters numeric,
  gps_accuracy_meters numeric,
  verified_nearby boolean not null default false,
  observed_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '45 minutes'),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.buzz_ground_truth (
  id uuid primary key default gen_random_uuid(),
  venue_id uuid not null references public.venues(id) on delete cascade,
  observed_at timestamptz not null,
  occupancy_band text not null check (occupancy_band in ('quiet','steady','busy','packed')),
  occupancy_pct smallint check (occupancy_pct is null or (occupancy_pct >= 0 and occupancy_pct <= 100)),
  queue_minutes integer check (queue_minutes is null or queue_minutes >= 0),
  observer_type text not null default 'field_observer',
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists buzz_provider_venues_provider_idx on public.buzz_provider_venues(provider, coverage_status);
create index if not exists buzz_signal_current_idx on public.buzz_signal_snapshots(venue_id, expires_at desc);
create index if not exists buzz_signal_source_idx on public.buzz_signal_snapshots(source, signal_type, observed_at desc);
create index if not exists buzz_score_fresh_idx on public.buzz_score_snapshots(expires_at, score desc);
create index if not exists partner_pulses_current_idx on public.venue_partner_pulses(venue_id, expires_at desc);
create index if not exists user_reports_current_idx on public.buzz_user_reports(venue_id, expires_at desc);
create index if not exists ground_truth_venue_time_idx on public.buzz_ground_truth(venue_id, observed_at desc);

alter table public.buzz_provider_venues enable row level security;
alter table public.buzz_provider_events enable row level security;
alter table public.buzz_signal_snapshots enable row level security;
alter table public.buzz_score_snapshots enable row level security;
alter table public.venue_partner_pulses enable row level security;
alter table public.buzz_user_reports enable row level security;
alter table public.buzz_ground_truth enable row level security;

-- Public clients only need the already-sanitized score snapshot. All raw evidence
-- remains server-side and is written with the Supabase service role.
drop policy if exists "public can read current buzz scores" on public.buzz_score_snapshots;
create policy "public can read current buzz scores"
on public.buzz_score_snapshots for select
using (expires_at > now() - interval '10 minutes');

create or replace view public.buzz_current_signals as
select *
from public.buzz_signal_snapshots
where expires_at > now();
